apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
 generateName: jmeter-perfload-task-
spec:
 entrypoint: jmeter-task
 templates:
 - name: jmeter-task
   container:
     image: deepaksinghvi/jmeter-image:1
     command: ["/bin/sh"]
     args: ["/app/entrypoint.sh", "https://raw.githubusercontent.com/deepaksinghvi/jmeter-one-off-dyno/main/test/jmeter_on_aws.jmx"]
